### ISSUE TITLE
Mobs immune to bullets while energy netted.

### ISSUE THREAD

**Issue by HzDonut** [VOREStation/VOREStation#2615] opened 2017-12-24 11:27 UTC
#### Brief description of the issue
While out hunting gaslamps, I aggroed one and a fellow scientist energy netted them...and my bullets started doing no damage at all, the gaslamp only died because they started to crowbar the hell out of it. Went through an entire magazine of ammo in the prototype SMG and an entire box after that before giving up. On a gaslamp that has no net, it dies in three 3-round burst volleys if they all hit. I was also recently informed it's ALL mobs that are netted.

#### What you expected to happen
I shoot the mob, it dies.

#### What actually happened
It became a speedy bullet immune monster that wanted to kick my ass.

#### Steps to reproduce
- Aggro a mob
- Use the 'Hunter' gun to energy net it.
- Shoot it with bullets.
- Hope to god someone is there to melee it or else you'll be hunted forever by an immortal monster.

#### Code Revision
-  release - 
d2194a759af92a64e9392232841f351bf15d409f 

 
#### Anything else you may wish to add:
- Recommend trying out energy weapons as well.

**Comment by Screemonster** [comment] 2017-12-24 11:31
I've noticed this with grubs as well. I was detective and had my revolver out, when the person that let me into the department decided to help by netting it.

Cue an angry grub chasing them around the department in circles where I couldn't actually line up a shot on it without risking hitting them instead.

I think it's _intended_ to stop using the energy net as a OHKO to cheese mob-combat areas like the presently-defunct wilderness.

**Comment by HzDonut** [comment] 2017-12-24 11:33
...which wouldn't be a problem if the buckled issue weren't around, I suppose. Until that's fixed though this is quite the problem, eh?

**Comment by Screemonster** [comment] 2017-12-24 12:22
Duplicate of #2307

**Closed** 2017-12-24 14:44 UTC
Labels: Status: Duplicate
