### ISSUE TITLE
[GENERAL] Shadekin cannot save preferred language as Galactic Common in character setup

### ISSUE THREAD

**Issue by CubeJackal** [VOREStation/VOREStation#15042] opened 2023-06-18 10:38 UTC
#### Brief description of the bug
Shadekin (and BESKs) cannot save their preferred language as Galactic Common in character setup, or have Galactic Common as their preferred language by default when spawning in. Other languages appear to save as normal when set as preferred, and Galactic Common can be chosen as a preferred language in-game as normal.

#### What you expected to happen
For Galactic Common to save to the character slot as the character's preferred language.

#### What actually happened
The preferred language resets to Shadekin Empathy when saving the slot or spawning in.

#### Steps to reproduce
- Create a shadekin or BESK character slot
- Set preferred language as Galactic Common
- Attempt to save the slot or enter the round
 
#### Anything else you may wish to add:
Since setting preferred language in-game still works, this is more of an inconvenience than a serious issue.

**Comment by KillianKirilenko** [comment] 2023-06-18 11:23
Duplicate of/related to #14815

**Closed** 2023-07-01 23:32 UTC
Labels: Type: Bug
