### ISSUE TITLE
Belly Transfer Bug

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#1355] opened 2017-04-06 21:27 UTC
#### Brief description of the issue
With the auto transfer feature in the vore panel, sometimes people fail to transfer, and are stuck in limbo.

#### What you expected to happen
For the person resisting to move from one belly to another

#### What actually happened
They disappeared from all bellies, but did not die, or get released

#### Steps to reproduce
- Have someone in a vore belly with a transfer chance and target set
- Have that person resist until they achieve that transfer effect
 
#### Anything else you may wish to add:
May require multiple attempts to reproduce, as it doesn't seem consistent. Sometimes they transfer successfully, other times they get stuck in limbo.
They can use OOC escape to get out of limbo, so it's not super important. It just isn't working right, so I thought to make a report.

**Comment by SpadesNeil** [comment] 2017-04-07 01:04
Duplicate of #763

**Closed by SpadesNeil** 2017-04-07 01:04 UTC
