### ISSUE TITLE
Whispering bugs, not fully tested

### ISSUE THREAD

**Issue by Vae42** [VOREStation/VOREStation#149] opened 2016-05-21 18:37 UTC
#### Brief description of the issue
Very specific whispers cant be heard. When I (A normal sized person) Scoop up a tiny person, I can no longer hear their whispers. The problem persists when the tiny is placed in a vore belly. 

#### What you expected to happen
To hear said whispers

#### What actually happened
I saw no text displayed when they sent whispers(confirmed by 3rd party chat)
#### Steps to reproduce
(This may be repeatable in other context, but my specific issue came about in this precise way recreatably)
1. Be normal sized
2. click on a tiny (smallest sized character sprite) to pick them up
3. make them whisper something
4. (optional) Put them into a belly (mine was a custom one) 
5. repeat step 3
6. ???
7. Profit

#### Additional info:
 - Unknown
 - 2nd bug report. hope I did it right this time
- edited to add steps

### Spades Edit:
Similar issue as of 3bb482e

Reportedly, a predator using sleeper belly as a dogborg got one message randomly and then the rest didn't go through. The predator and prey could not hear emotes or speech from each other.

Only one LOOC message, too.

**Comment by SpadesNeil** [comment] 2016-05-21 18:53
Need steps to reproduce but otherwise good.

Can you provide the steps in a 1, 2, 3 (etc) format to reliably recreate the bug?

**Comment by SpadesNeil** [comment] 2016-05-23 04:44
Still an issue as of https://github.com/VOREStation/VOREStation/commit/3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e

Reportedly, a predator using sleeper belly as a dogborg got one message randomly and then the rest didn't go through. The predator and prey could not hear emotes or speech from each other.

Only one LOOC message, too.

**Comment by Arokha** [comment] 2016-05-23 04:47
Um, I’m unsure how LOOC would be affected. I didn’t change it. Also when testing this I tested it with like 10 emotes. Are you sure this wasn’t an isolated incident?

**Comment by SpadesNeil** [comment] 2016-05-23 04:47
I'm not sure, but I know GaleTempest is having significant problems with it in-game right now.

**Comment by SpadesNeil** [comment] 2016-05-23 04:48
Marking as blocker because if it's really a bug, it's blocking RP entirely.

**Comment by SpadesNeil** [comment] 2016-05-24 00:53
Confirmed not to be an isolated incident. Players are complaining of this bug. Upgrading to extreme severity.

**Comment by Arokha** [comment] 2016-05-31 18:23
This was fixed when I rewrote all of Polaris' saycode 6 days ago, which has been merged, and will appear in the next update.

**Closed by Arokha** 2016-05-31 18:23 UTC
Labels: BLOCKER, Pri: 4-Extreme, Type: Bug, Vore-Related
