### ISSUE TITLE
Neutral traits secretly counting towards max

### ISSUE THREAD

**Issue by ktccd** [VOREStation/VOREStation#2318] opened 2017-10-18 11:25 UTC
#### Brief description of the issue
Neutral traits count towards the max, giving an incorrect error message when trying to spawn a character with them secretly adding more to the stats.

#### What you expected to happen
0 traits left and 0 points left should be able to join in.

#### What actually happened
Neutral traits still counted, disabling joining.

#### Steps to reproduce
- (Step 1) Select 5 traits adding up to a legal combination.
- (Step 2) Select a neutral trait, such as auto-hiss or metabolism.
- (Step 3) Try to join a round.

#### Code Revision
551371f8adcd2620447b2e4099ddf96c1125c0b5

**Comment by Cameron653** [comment] 2017-10-18 18:22
That code revision you have in the PR is from 16 days ago. This should be fixed on the new release.

**Comment by SpadesNeil** [comment] 2017-10-18 23:33
Duplicate of https://github.com/VOREStation/VOREStation/issues/2258 I think anyway

**Closed by SpadesNeil** 2017-10-18 23:33 UTC
Labels: Task: Needs Testing, Type: Bug
