### ISSUE TITLE
Monkeys Clone on cooking

### ISSUE THREAD

**Issue by Benemuel** [VOREStation/VOREStation#939] opened 2017-02-10 10:53 UTC
#### Brief description of the issue
Monkeys, when cooked, do not turn into the cooked item, but spawn a item and come out.

#### What you expected to happen
Monkeys to not be infinite food.

#### What actually happened
Infinite monkey pizza.

#### Steps to reproduce
- (Step 1)Grab a monkey, or farwa, or whatever
- (Step 2)Deep fry/cerealize/whatever
- (Step 3) Watch infinite monkey food.

#### Code Revision
- Server revision: release - 2017-02-03
df3c823953c6a7c9b27cd6b56b7c1356f0752b72
 
#### Anything else you may wish to add:
- As nice as the infinite food is, this is a little jarring to say the least to do.

**Comment by SpadesNeil** [comment] 2017-02-10 18:19
Duplicate of https://github.com/VOREStation/VOREStation/issues/810

**Closed by SpadesNeil** 2017-02-10 18:19 UTC
