### ISSUE TITLE
camera's photos don't show sprites in V4 caves

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3671] opened 2018-05-11 13:21 UTC
#### Brief description of the issue
the photos only show the ground, nothing on it such as corpses, crystals or anything else

#### What you expected to happen
To have something worth while to write a report with

#### What actually happened
I had pictures of sand

#### Steps to reproduce
- (Step 1)go to virgo 4 cave
- (Step 2) find POI, dead thing, or crsytals
- (Step3) enjoy your picture of dirt

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 849c1374a1b064b9c9a1fb8c1c43ed19a4259100 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment] 2018-05-11 13:51
Duplicate of #3529

**Closed by Arokha** 2018-05-11 13:51 UTC
