### ISSUE TITLE
[GENERAL] Scannable Overmap Objects Default To [GENERIC] Item When Scanned

### ISSUE THREAD

**Issue by ResidentCody** [VOREStation/VOREStation#14762] opened 2023-04-06 21:57 UTC
#### Brief description of the bug
Scanning a manually created, unidentified "/overmap/visitable/..." object does not retain appropriately set sprites and sometimes potentially fails to retain custom description entries as well.

#### What you expected to happen
When scanning an un-scanned overmap object, for the object being scanned to switch from an 'unscanned' icon_state/description to a 'scanned' icon_state/description.

#### What actually happened
When scanning an un-scanned overmap object (such as a ship or other unidentified object) using ship scanners, the target may switch to a GENERIC ITEM green box icon_state instead of retaining any preconfigured vars for what icon should be displayed upon scanning.

#### Steps to reproduce
- Place a /obj/effect/overmap/visitable/admin_use/ item, then configure it with some manner of custom text/icon_state in vars
- Use a ship's/shuttle's sensors to scan the object
- Notice that it doesn't properly turn into the desired icon_state/info and instead turns into a generic item icon_state

**Comment by Runa-Dacino** [comment] 2023-04-07 12:24
Partially fixed by https://github.com/VOREStation/VOREStation/pull/14616

To avoid unscanned name and description from being returned to defaults, use
`real_name`
and
`real_desc`

Bug is caused by get_scan_data() setting name, desc, icon etc to initial(var), which is defined at compile-time, thus rejecting runtime edits. Using real_name, real_desc etc overrides this behaviour.

**Closed** 2023-04-10 00:55 UTC
Labels: Type: Bug
