### ISSUE TITLE
Vents and Scrubbers render above water tanks

### ISSUE THREAD

**Issue by Jakksergal** [VOREStation/VOREStation#4014] opened 2018-07-12 14:07 UTC
#### Brief description of the issue
Water tanks and welding fuel tanks render below floor vent pumps and scrubbers.

#### What you expected to happen
To have some kind of spacial consistency.

#### What actually happened
Muh imershun was broken

#### Steps to reproduce
- Place fuel tank or water tank on the same tile as a secured vent or scrubber.
- That's literally the only step.

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c 
 
#### Anything else you may wish to add:
- Tested in the janitor's closet with their starting water tank and the fuel tanks nearby in maintenance. Tested with a scrubber and vent both in the janitor's closet and in the hall outside.
- May just be a mapping anomaly where someone used the wrong type of vents but I'm unsure. If needed, I can test water tanks on multiple levels.

**Comment by Heroman3003** [comment] 2018-07-12 20:35
That's a duplicate of #3719, isn't it?

**Comment by SpadesNeil** [comment] 2018-07-12 21:15
Affirmative.

**Closed by SpadesNeil** 2018-07-12 21:15 UTC
