### ISSUE TITLE
Certain character setups crash people. Again.

### ISSUE THREAD

**Issue by Cameron653** [VOREStation/VOREStation#2419] opened 2017-11-05 03:54 UTC
#### Brief description of the issue
People being crashed by certain character setups ghosting around.

#### What you expected to happen
Not crash

#### What actually happened
Crash

#### Steps to reproduce
- Ghost around
People crash
Character used: https://i.imgur.com/48RpVUK.png

#### Code Revision
- 222337a2acf61ffc50a3fe265a70f3bc1ba2b625 
 
#### Anything else you may wish to add:
-

**Comment by SpadesNeil** [comment] 2017-11-05 04:38
For fuck's saaaaaaake.

**Comment by OrbisAnima** [comment] 2017-11-06 14:45
Looks like something new though

**Comment by SpadesNeil** [comment] 2017-11-08 15:16
Closing this as a dupe of https://github.com/VOREStation/VOREStation/issues/2186

**Closed by SpadesNeil** 2017-11-08 15:16 UTC
Labels: Pri: 1-Blocker, Type: Bug
