### ISSUE TITLE
Escape pods are completely useless and broken

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#1989] opened 2017-08-12 19:54 UTC
#### Brief description of the issue
Escape pods are unusable.

#### What you expected to happen
During emergency evac, for the escape pods to unbolt and open up.

#### What actually happened
Even when the shuttle had arrived, the escape pods did not launch. They also did not launch when armed. They had to be manually ejected after hacking our way into the pods.

#### Steps to reproduce
- Emergency evac.
- Go to escape pods.
- Can't board escape pods. Hack them.
- Arm escape pods.
- Escape pods won't launch. Manually eject.

#### Code Revision
- https://github.com/VOREStation/VOREStation/commit/690bca044d7377ea0c755a240cf32f3747ffabac

**Comment by Novacat** [comment] 2019-04-18 21:54
Duplicate of #3401, keeping 3401 open as it is more up to date with our map.

**Closed by Novacat** 2019-04-18 21:54 UTC
Labels: Sev: 2-High, Status: Duplicate, Type: Bug
