### ISSUE TITLE
Spawn Character uses wrong body type

### ISSUE THREAD

**Issue by Dhaeleena** [VOREStation/VOREStation#951] opened 2017-02-14 12:05 UTC
#### Brief description of the issue
When you admin spawn a female character they spawn with a male body

#### What you expected to happen
When an admin spawns a character silently for whatever reason to actually use the female Body Type

#### What actually happened
My spawned characters always use the Male body type

#### Steps to reproduce
- Have admin perms
- Special Verbs>Spawn Character
- Spawn it and see how you are lacking your boobs and female body sprite

#### Code Revision
- release - 2017-02-03
df3c823953c6a7c9b27cd6b56b7c1356f0752b72 
 
#### Anything else you may wish to add:
- I think this might happen because the character creation screen does the same thing, You will never see your character preview using a female body (on most races) on the character creation menu

**Comment by SpadesNeil** [comment] 2017-02-14 20:00
Duplicate of https://github.com/VOREStation/VOREStation/issues/611

**Closed by SpadesNeil** 2017-02-14 20:00 UTC
