### ISSUE TITLE
Tajara Mining Voidsuit. Chest piece bugged.

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#254] opened 2016-05-31 14:30 UTC
#### Brief description of the issue
The Refitted Mining Voidsuit chest piece doesn'T show up. You can put it on and hold it et cetera. But the sprite doesn't show on the character ( The Tajara voidsuit ) It still protects though!

#### What you expected to happen
To see that beautiful Tajara voidsuit. 

#### What actually happened
I got to see the ugly RD uniform I was wearing. Cried in a corner once more.

#### Steps to reproduce
Grab a Voidsuit. Not sure if it's all voidsuits. Would have to test, but grab a mining voidsuit. Put it in the cycler and refit it to Mining, Tajara. Both helmet and chest piece. Then attach the helmet to the chest piece and put it on. Whew. You won'T see the sprite. Still works though

#### Additional info:
Server revision: release - 2016-05-23

**Comment by killer653** [comment] 2016-05-31 14:58
Duplicate of issue #230. 
PR #234 fixed this in the master code

**Closed** 2016-05-31 15:00 UTC
Labels: Duplicate
