### ISSUE TITLE
Vulpkanin has a sprite issue

### ISSUE THREAD

**Issue by kcin2001** [VOREStation/VOREStation#453] opened 2016-08-08 02:38 UTC
#### Brief description of the issue
on the north facing sprite or looking at their back they are missing some pixels leaving them transparent
#### What you expected to happen
for them to not be missing pixels
#### What actually happened
missing pixels
#### Steps to reproduce
look at the vulpkanin sprite 
![image](https://cloud.githubusercontent.com/assets/16435949/17467746/677bf638-5cd6-11e6-8096-e885286c7e19.png)

#### Additional info:
 - **Server Revision**: a3835cb52f954f5278d7987f458f75fa90ce61c7 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment] 2016-08-08 15:46
Duplicate of https://github.com/VOREStation/VOREStation/issues/296

**Closed by SpadesNeil** 2016-08-08 15:46 UTC
