### ISSUE TITLE
[MAPPING] AI core loses power on SD

### ISSUE THREAD

**Issue by ZodiacShadow** [VOREStation/VOREStation#13331] opened 2022-07-15 17:38 UTC
Stellar Delight AI core APC runs out of power.

The APC should receive power like every other APC.

Signed on as AI, instantly entered "no power" state. This has happened before. Signing on as an organic afterward let me attempt to fix it; it seems something with the core SMES doesn't register as wired right; removing and replacing the wire under the SMES let it start to power the APC as normal.

Server revision: B:release D:
Commit: [90dfb2d4e7c4f7339d9d590b9c8c9fa3db24b68a]

**Comment by Heroman3003** [comment] 2022-07-16 23:58
removing and re-adding wire under smes should do the trick if it happens again. I do not know the cause and it happens completely randomly (and only on SD too and with different SMES on z3?) so I cant even begin approaching fixing it; but that is an in-round solution.

**Comment by Heroman3003** [comment] 2023-06-28 21:53
This appears to not have reoccured in a long time so I will be closing this. Not sure what ended up fixing it though.

**Closed by Heroman3003** 2023-06-28 21:53 UTC
Labels: Type: Bug, Type: Map
