### ISSUE TITLE
Cyborgs can't see minerals well

### ISSUE THREAD

**Issue by ktccd** [VOREStation/VOREStation#2954] opened 2018-02-03 09:37 UTC
#### Brief description of the issue
Cyborgs using the built-in material scanner no longer gains the bonus light effect, which means they can only see minerals which have light on them already.
This means they can only see the ones that are nearby on the outside, which they could see anyway.

#### What you expected to happen
I expected to see the ores in the walls using the material scanner module thing.

#### What actually happened
I could only see ores that I could've seen without the module anyway.

#### Steps to reproduce
- (Step 1) Be a mining cyborg and equip the module to see things in walls.
- (Step 2) Go outside to the mining area and look for a vain.
- (Step 3) Observe that you'll only see the outermost ores, which you would've seen anyway.

#### Code Revision
- e02a95743ea876a356e1bea409e9c738e0a09652

**Comment by Arokha** [comment] 2018-02-15 09:11
https://github.com/PolarisSS13/Polaris/pull/4834

**Comment by Arokha** [comment] 2018-02-15 09:44
Duplicate of #2805 too

**Closed by Arokha** 2018-02-15 09:44 UTC
Labels: Status: Duplicate
