### ISSUE TITLE
Alien whitelist is broken. AGAIN.

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#427] opened 2016-07-22 05:28 UTC
#### Brief description of the issue
Alien whitelist is being incorrectly enforced.

#### What you expected to happen
Players not to be allowed to join as Xenochimera and the like without being on the whitelist.

#### What actually happened
Players not allowed to play Akula as well.
Prometheans are also blocked.
Vulpkanins are blocked.
Tajaran are blocked.

#### Steps to reproduce
Have a non-admin player try to join as restricted species. (Vox, Xenochimera)

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/b3b0ae6660b10c9abdc67772eb98d08f61bc51b0
 - **Anything else you may wish to add**: The person who discovered this bug didn't report it correctly.

Edit: Turned on the whitelist. Now people can't play as Akula. I am awaiting further complaints to see what else is broken.

**Comment by Cameron653** [comment] 2016-07-22 16:30
The whitelist is currently off due to every single species except for humans being whitelisted, even though the is_whitelisted tag was removed from them due to how the whitelist works.

The whitelist error has been fixed in the newest polaris. All we need to do is upgrade to the newest polaris and enable the whitelist to fix this.

**Comment by SpadesNeil** [comment] 2016-08-14 04:17
This isn't working.

**Comment by kcin2001** [comment] 2016-08-14 04:21
also prometheans are whitelisted

**Comment by ArcanaFilippone** [comment] 2016-08-14 04:23
vulpkanins and Tajara are whitelisted as well

**Comment by Cameron653** [comment] 2016-08-14 04:48
Working on a fix currently

**Comment by Cameron653** [comment] 2016-08-14 06:15
Emergency hotfix I made fixes this to work as intended, BUT this is more of a bandaid fix than a perm fix.

Basically, it makes it so if you're able to select a race (Any race that has SPECIES_CAN_JOIN and doesn't have SPECIES_IS_WHITELISTED) you'll be able to join in as.

If a non-whitelisted user tries to select a whitelisted race, this'll pop up: http://puu.sh/qAHIM/cdbf98937d.png

The whitelist system prevents unwhitelisted people from selecting a whitelisted race, but if a person's savefile has the race already selected they'll be able to spawn in as it (Or if their savefile is edited so their species is a whitelisted race)

**Closed** 2016-08-14 06:28 UTC
Labels: BLOCKER, Pri: 4-Extreme, Resolved, Type: Bug
