### ISSUE TITLE
Usage of apostraphe over comms changes languages, rather than the assigned key doing so.

### ISSUE THREAD

**Issue by BonniePandora** [VOREStation/VOREStation#13113] opened 2022-06-19 01:46 UTC
#### Brief description of the bug
Speaking over comms and using any grammatically correct contractions results in the messages coming out as a half-gibbered mess after any `'`'s featured.

#### What you expected to happen
To be able to speak like a normal person over comms.

#### What actually happened
My character, alongside many others, managed to produce half a sentence of coherent speech in one language, before changing to another mid-sentence past any apostrophes.

#### Steps to reproduce
- Spawn in
- Speak over radios with a message like "You're all nerds."
- Watch as everything after the ' is gibberish in another language.

#### Code Revision
- Server revision: B:release D:
Commit: [60f031b10d8956a3b6ee5af3ea1be1bca04d91eb](http://127.0.0.1:53057/tmp8140/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/60f031b10d8956a3b6ee5af3ea1be1bca04d91eb%22%3Ehttps://github.com/VOREStation/VOREStation/commit/60f031b10d8956a3b6ee5af3ea1be1bca04d91eb%3C/a%3E)

**Comment by ItsSelis** [comment] 2022-06-19 01:47
Most likely a duplicate of  #11390

**Closed** 2022-06-19 03:58 UTC
Labels: Type: Bug
