### ISSUE TITLE
Bread and cake slices in loadout lunchboxes are actually made of paper

### ISSUE THREAD

**Issue by SingoDingo** [VOREStation/VOREStation#2614] opened 2017-12-24 08:33 UTC
#### Brief description of the issue
Things like cake and meatbread slices that are spawned in lunchboxes are consumed in one bite and provide no nutriment.

#### What you expected to happen
Eat my meatbread slice and be happy that it actually did anything.

#### What actually happened
Bright red text said "None of the meatbread slice left!" and the entire slice vanished in my hand.

#### Steps to reproduce
- Get a lunchbox from the loadout.
- Customize it to have cake/meatbread.
- Attempt to eat cake/meatbread, have it poof from existence upon touch.
- Cry a little on the inside.

#### Code Revision
085be926758a3696c4321774851f528c422ced40

**Comment by Screemonster** [comment] 2017-12-24 08:35
Duplicate of #2584

**Comment by SingoDingo** [comment] 2017-12-24 10:02
Ah, fair! Shall I delete this one?

**Closed** 2017-12-24 14:43 UTC
