### ISSUE TITLE
Cargo Shuttle Conveyor belt doesn't work!

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#3419] opened 2018-04-10 00:32 UTC
#### Brief description of the issue
When the cargo bay's conveyor belt is active, the cargo shuttle's belt does not activate when they come into contact.

#### What you expected to happen
The conveyor belt to move crates along into the shuttle!

#### What actually happened
Crates stop half-way in because the cargo shuttle's conveyor belts do not work.

#### Steps to reproduce
- Call cargo shuttle and wait for it to arrive.
- Pull the levers for both conveyor belts.
- Only the bay's conveyor belt will run, the cargo shuttle will remain inactive.
#### Code Revision
0b4a7e3a7ea4baed068ae7fcd1ce68a4632a2fc8 
 
#### Anything else you may wish to add:
N/A

**Comment by Arokha** [comment] 2018-04-10 00:35
dupe of #3031 sorry resh

**Closed by Arokha** 2018-04-10 00:35 UTC
Labels: Status: Duplicate
