### ISSUE TITLE
General bugs

### ISSUE THREAD

**Issue by Nekri** [VOREStation/VOREStation#476] opened 2016-08-14 13:05 UTC
these are just a couple problems I ran into the past few days

Digestion has kinda been on the fritz especially for borgs like the canine units

if you cook a micro the cooked sprite turns normal sized not micro anymore

sometimes escaping a grasp when micro leaves you stuck and having to re-spawn. you simply dont exist

also cannot force feed self to Ian the dog, not sure about other animals know you can to monkey tho

**Comment by SpadesNeil** [comment] 2016-08-14 16:51
Duplicate of https://github.com/VOREStation/VOREStation/issues/466

Please do not include multiple issues in the same post.

Please also do not ignore the format given to you by Github for reporting bugs.

**Closed by SpadesNeil** 2016-08-14 16:51 UTC
