### ISSUE TITLE
Maintenance drones and item stripping

### ISSUE THREAD

**Issue by ArgobargSoup** [VOREStation/VOREStation#700] opened 2016-11-04 03:13 UTC
#### Brief description of the issue
In certain cases, trying to steal a hat from a drone can end up causing a functional item stripping menu to appear on the drone's screen.

#### What you expected to happen
To sit there and have my hat stolen when the thief eventually remembered how to steal it.  (Darn law 3.)

#### What actually happened
An item stripping window popped up during the theft attempts, despite the fact that I hadn't clicked on anything.  I was able to use said window, too, emptying the thief's pockets.  (oh dear, law 3, whoops)

#### Steps to reproduce
Have someone attempt to steal stuff from you as a drone.  May need some weird clickin'.

#### Additional info:
 - **Server Revision**: release - 2016-10-22
6f3cb6bf7b33650a94068197e238f07f546e9567 
 - Accordin' ta earlier comments from the hat thief, apparently he was getting a limited item stripping menu that didn't involve the hat slot on some of his failed past attempts.

**Comment by SpadesNeil** [comment] 2016-11-05 01:28
So this isn't a duplicate of https://github.com/VOREStation/VOREStation/issues/688 ?

**Closed** 2016-11-23 16:57 UTC
Labels: Status: Duplicate, Type: Polaris Bug
