### ISSUE TITLE
SPAM!

### ISSUE THREAD

**Issue by Prawneen** [VOREStation/VOREStation#286] opened 2016-06-03 20:44 UTC
#### Brief description of the issue
Attempting to combine steel rods with cable coils spams the number 1 in the chat. For everyone to see.
https://i.gyazo.com/84d4dceee682ed212845405d16cf1794.png
#### What you expected to happen
To get a stun prod thingy

#### What actually happened
Spammed 1 in chat for everyone to see

#### Steps to reproduce
Combine steel prod and cable coil

#### Additional info:
Server revision: release - 2016-06-01
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment] 2016-06-03 20:48
That is hysterical.

**Comment by SpadesNeil** [comment] 2016-06-03 21:06
Yosh from Polaris reports he cannot reproduce. Need to test on ours.

**Comment by ursamedium** [comment] 2016-06-08 06:49
We have a similar one over on Eros, someone discovered it using glass on a cable coil yesterday. Haven't had a chance to investigate the bug, myself, but, since it;s such a weirdly specific thing, and I saw this, I figured I'd share! Assumed it was something from testing left over.
Hah. Weird shit. This might be my favorite bug though.

**Comment by Leshana** [comment] 2016-06-09 00:29
Pretty sure we pulled in fix for this from Polaris. Plox Confirm

**Comment by SpadesNeil** [comment] 2016-06-10 07:20
If this cannot be duplicated I will close this by next weekend.

**Comment by Arokha** [comment] 2016-06-10 14:17
Is duplicatable. I have a Polaris PR to fix it.

**Closed** 2016-06-10 15:14 UTC
Labels: Duplicate, Pri: 4-Extreme, Upstream Bug
