### ISSUE TITLE
Notice Board Description Missing

### ISSUE THREAD

**Issue by ktccd0** [VOREStation/VOREStation#9642] opened 2021-02-04 08:19 UTC
#### Brief description of the bug
When examining the Notice Board by the Cargo Desk, this text is shown:
You were unable to examine that. Tell a developer!

#### What you expected to happen
I expected anything but an error message.

#### What actually happened
I got an error message.

#### Steps to reproduce
- Go to cargo
- Examine the Notice Board
- ???
- Profit

**Comment by HzDonut** [comment] 2021-02-08 03:47
I did a flyaround on my fork and found that every noticeboard threw up this error. It's weird because in the code and even in VV the desc is set to ""A board for pinning important notices upon." so it really should be showing the description upon examine and I'm too much of a coding noob with .dm to figure out why that isn't happening. Also this is obj/structure/noticeboard and not obj/item/frame/noticeboard or obj/structure/noticeboard/anomaly spawned in by accident or anything

**Comment by Shadow-Quill** [comment] 2021-02-08 18:00
Duplicate of https://github.com/VOREStation/VOREStation/issues/9642

**Comment by ktccd0** [comment] 2021-02-09 08:17
man, I swear I searched for this issue before posting and found nothing O.o

**Comment by HzDonut** [comment] 2021-02-09 08:32
Should i repost over on that issue then?

**Comment by ktccd0** [comment] 2021-02-09 08:43
I think it didn't show up when I searched because I searched for "Notice board" not "Noticeboard".

**Closed** 2021-11-23 04:28 UTC
