### ISSUE TITLE
Teshari pick up broken

### ISSUE THREAD

**Issue by JemliRoivas** [VOREStation/VOREStation#721] opened 2016-11-13 18:48 UTC
#### Brief description of the issue
Teshari can currently only be picked up according to the macro micro size rules, which then meshes into their normal pick up coding, using the same sized sprite for being held or worn on the back.
#### What you expected to happen
Being able to pick up a same sized teshari the normal way.
#### What actually happened
Could only pick up a micro sized teshari, which then matched the size of the person picking them up.
#### Steps to reproduce
Have a teshari, try to pick them up.  Shrink the teshari down to micro size, pick them up successfully.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment] 2016-11-14 20:33
Marking as Won't Fix for now. The reason is this:
When you pick up a person, the thing you are holding is actually an object styled to look like them. They are inside the object. The object is called the 'holder'. Each species has a holder type that defines what sort of object they create when picked up.

The problem is... each species has \*A\* holder type. One. Setting Teshari to the normal Teshari holders means they can be scooped like normal stock Bay/Polaris Teshari, but... not when micro. Setting them to the vorestation custom micro holders makes them so they can be scooped when smaller like any other species. But you can't set it to 'both'. It's one or the other, unfortunately.

So... between the two, the VS specific custom micro holder makes more sense. Otherwise macros won't be able to pick up teshari without the drag-pickup things, they won't fit in backpacks and other stuff, even if they are the smallest size of micro.

**Closed** 2016-11-15 02:47 UTC
Labels: Status: Won't Fix, Type: Bug
