### ISSUE TITLE
Cyborg Charging Stations in Mech Bay

### ISSUE THREAD

**Issue by GodGivenDeath** [VOREStation/VOREStation#226] opened 2016-05-26 19:40 UTC
#### Brief description of the issue
The charging stations in the Mech Bay don't charge you.
#### What you expected to happen
I expected to recharge, as usually these are where one goes to do that, and one always expects them in the Mech Bay.
#### What actually happened
They won't charge because for some reason they have no charge themselves.
#### Steps to reproduce
Become borg, try to charge in Mech Bay. Alternatively, going in, either in character or as an observer/ghost, and examining the Cyborg Recharging stations. The charge meter will read as 0%, even if it is hours into the round and nobody has used it.
#### Additional info:
 - **Server Revision**: 3bb482ee56a4ade2e02fbb46fa3746728c9a3b3e 
 - I don't know this stuff, so I have no idea what could be wrong with it.

**Comment by Arokha** [comment] 2016-05-26 19:42
Duplicate of #202 (no offense)

**Comment by SpadesNeil** [comment] 2016-05-26 20:29
Re-opening this because this one is explained infinitely less badly than the other one.

**Closed** 2016-05-27 01:48 UTC
Labels: Pri: 3-Severe, Type: Bug
