### ISSUE TITLE
Arcade program is too loud

### ISSUE THREAD

**Issue by Little-119** [VOREStation/VOREStation#9529] opened 2020-12-28 08:56 UTC
#### Brief description of the bug
When someone plays the arcade program on their tablet (or presumably their laptop) in a public area, it's loud, distracting, and annoying, and as far as I'm aware there's no way to turn it off.

#### What you expected to happen
For the sound to only really be heard by the one playing the arcade program, or for the option to toggle the sound to exist, like how there's a toggle for most other potentially annoying sounds

#### What actually happened
arcade program do big annoy

#### Steps to reproduce
- have someone else get a tablet and play the arcade program in the same room as you

#### Code Revision
- b51953b032a4bfc9d84b5911f58760d6031b4745

**Comment by Shadow-Quill** [comment] 2021-02-08 17:59
Close to a duplicate of https://github.com/VOREStation/VOREStation/issues/9529

**Closed** 2021-02-19 13:32 UTC
