### ISSUE TITLE
Micros put in Footwear immediately fall out

### ISSUE THREAD

**Issue by BigBababooey** [VOREStation/VOREStation#11304] opened 2021-07-30 12:01 UTC
#### Brief description of the bug
When a micro is stuffed into a boot, or any other form of footwear, it will put the message of them being stuffed in, then they merely fall to the ground.

#### What you expected to happen
The original behavior of the micro being stored in the footwear, akin to how one would with a knife, being given occasional bits of redtext.

#### What actually happened
Simply put the text of stuffing the micro gets put in the chat, then either immediately or within a second or so, they pop out onto the ground as if they had been dropped, instead of being carried along.

#### Steps to reproduce
- Pick up a player with sufficient size difference
- Click on footwear either being worn or held
- Micro should fall out

#### Code Revision
- Server revision: B:release D:
Commit: d241b09bc4e1991f7e3bbccf36058f72e46f4162 

#### Anything else you may wish to add:
- Only currently tested on one character, my micro shark Keta, possible odd setting interaction present I am not aware of, though only thing disallowed is Spontaneous TF, so this is unlikely.

**Comment by Arokha** [comment] 2021-07-30 13:21
Duplicate of #11172

**Closed by Arokha** 2021-07-30 13:21 UTC
Labels: Status: Duplicate
