### ISSUE TITLE
Micros and Drones misaligned on tables and chairs

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#138] opened 2016-05-21 14:29 UTC
#### Brief description of the issue

Micros (and drones), when standing on tables, appear to be under the tables. Similar problem when buckled to chairs.
#### What you expected to happen

When a micro or drone is on the table, they should appear, you know, ON THE TABLE. Or chair. So, in the center of the tile.
#### What actually happened

They don't. They stay at the bottom of the tile. I think this looks stupid. It makes it look like they're under the table's edge.
#### Steps to reproduce

Climb on a table as a micro or drone. Or, buckle yourself to a chair.
#### Additional info:
- **Server Revision**: Unknown! Fix this!
- **Anything else you may wish to add**: Can we check if we're standing on a table, and adjust the pixel_y axis accordingly?

**Comment by nightwingthedragon** [comment] 2016-05-21 16:34
I'm a little curious about this one, because I remember it being one of the reasons behind making micros be centred on a tile rather than aligned to the bottom. What are your thoughts about letting micros be aligned to the bottom of a tile again unless they're on a table or chair?

**Comment by Arokha** [comment] 2016-05-21 16:36
Making them only be aligned on a table or chair would require checking repeatedly what they are on against a list of things they should be centered on, which would be somewhat intensive. It should probably be one or the other, though I'm indifferent personally.

**Comment by nightwingthedragon** [comment] 2016-05-21 17:13
For getting onto a table, adding this check would be no problem, but using the "climb" button isn't the only way to get onto a table. The easiest way I can think of is to have a constant check going in life.dm with some pretty big snowflake code saying "constantly check which tile the player's in, and if they're on  a table AND micro, adjust their pixel_y" - which is, as Arokha said, very CPU-intensive.

**Comment by SpadesNeil** [comment] 2016-05-21 17:17
Being buckled to a chair sends a command to the mob, and climbing onto a table also sends commands to the mob saying you can pass over tables. These commands can cause the pixel changes. The drones are the ones who will be a bitch to fix.

**Comment by nightwingthedragon** [comment] 2016-05-21 21:58
Well yes, but micros can also be placed on tables by humans, and anyone can be grab-clicked onto a table too.

**Comment by Arokha** [comment] 2016-05-21 22:08
The problem is that when you're unbuckled or step off a table there's nothing to reset your pixel_x/y. It'd be better if it was just, you know. Just always in the middle like it was before.

**Comment by nightwingthedragon** [comment] 2016-05-21 22:11
Unfortunate, but true.

**Comment by SpadesNeil** [comment] 2016-05-21 22:19
Drones should be adjusted to be consistent as well. The positioning of drones always annoyed the shit out of me, especially when other servers usually use center-of-tile.

**Comment by nightwingthedragon** [comment] 2016-05-21 22:23
I don't wanna turn this whole place into a position-in-tile debate again, but I'm somewhat in favour of having all small creatures aligned to the bottom of the tile to make it easier to see the size difference. But we can make a forum thread or something about that.

**Comment by Arokha** [comment] 2016-05-21 23:50
No issues that can't be worked on.

So are we doing center of tile or bottom? Or shall we close this and have a discussion on a forum thread?

**Comment by Jwguy** [comment] 2016-08-02 08:38
I say Center-of-Tile~! It is tried and proven, and I find it helps ease up on overlap with a lot of other sprites, too!

**Closed** 2017-01-06 02:31 UTC
Labels: Pri: 1-Minor, Status: Won't Fix, Type: Bug
