### ISSUE TITLE
Soda Dispenser in Bridge Meeting Room has no cartridges

### ISSUE THREAD

**Issue by KotetsuRedwood** [VOREStation/VOREStation#1781] opened 2017-06-23 22:41 UTC
#### Brief description of the issue
The soda dispenser in the Bridge Meeting Room has no cartridges installed

#### What you expected to happen
Put in a paper cup and get a cool, refreshing glass of Cole or Bepsi or Hot Dr. Pepper

#### What actually happened
Put in a paper cup and get **disappointment**

#### Steps to reproduce
1. Go to bridge meeting room somehow.
2. Look at cartless dispenser.
3. Weep.

#### Code Revision
Server revision: release - 
256e1db4d6e43368e3e53cf3027e5ae395abdacd 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://user-images.githubusercontent.com/10330701/27502642-7ebb042c-586d-11e7-8a48-5350267328d0.png)

**Comment by AeroWing** [comment] 2017-06-24 04:01
@JoanRisu and @somekindofpony will both advocate the installation of 32 of our finest cartridges containing only the _QUENCHIEST_ of beverages.

**Comment by Cameron653** [comment] 2017-06-30 06:48
Marking as map due to this being caused by an unloaded soda dispenser

**Closed** 2017-07-09 15:15 UTC
Labels: Pri: 4-Minor, Status: Resolved, Type: Map
