### ISSUE TITLE
Invisible atmospheric tape

### ISSUE THREAD

**Issue by FirstSgtDan** [VOREStation/VOREStation#147] opened 2016-05-21 17:35 UTC
There's a door I can't go through at 160/201, I receive the message "You are not supposed to go past the atmospherics tape..." but there isn't even a tape.

https://gyazo.com/930f28099a2ee46e6e9627466e2a16cb

**Comment by Arokha** [comment] 2016-05-21 17:41
Duplicate of #128

**Closed by Arokha** 2016-05-21 17:41 UTC
