### ISSUE TITLE
Infection Not clearing

### ISSUE THREAD

**Issue by Nekri** [VOREStation/VOREStation#503] opened 2016-08-22 04:31 UTC
#### Additional info:
- **Server Revision**: Server revision: release - 2016-08-14
  46b3bb734538fe50433122d41fdd741522aa55f5

**Comment by SpadesNeil** [comment] 2016-08-23 01:06
Eugh, that's a nasty bug. Needs some testing, but this should be fixed ASAP if it's happening.

**Comment by Cameron653** [comment] 2016-08-23 11:34
I can confirm this randomly occurs on station. I can never find out the
cause, it's most likely something to do with how germ code works.

**Comment by SpadesNeil** [comment] 2016-08-23 16:55
Surely it isn't random. There must be a reproduceable cause.

**Comment by Cameron653** [comment] 2016-08-23 18:24
There most likely is, but from the two times I've seen it occur I didn't
see any cause for the germs to just sit at the level they were at.

Better documentation next time it occurs could probably help find out the
cause. (Ex damage type, time after taking damage, any meds injected)

Every other time I've seen infections they healed naturally

**Comment by SpadesNeil** [comment] 2016-08-23 18:32
Marking this as poorly explained for now just because we don't know what is going on either.

**Comment by SpadesNeil** [comment] 2016-12-10 20:54
Needs re-testing.

**Closed** 2017-01-02 08:05 UTC
Labels: Status: Cannot reproduce, Task: Explain better, Type: Bug
