### ISSUE TITLE
Agent Cards do not update their sprites accordingly when changing appearance.

### ISSUE THREAD

**Issue by ItsTheKet** [VOREStation/VOREStation#11120] opened 2021-07-17 08:19 UTC
#### Brief description of the bug
The appearance shifting functionality of Agent Cards appears to be non-functional, giving the message of changing appearances but not updating the sprite properly

#### What you expected to happen
Be able to change the appearance of agent ID's when the need arises.

#### What actually happened
Realize that it doesn't ACTUALLY change it's appearance anymore.

#### Steps to reproduce
- Obtain Agent Card
- Edit Agent Card
- Click and set appearance
- Obtain confirmation message of the appearance having changed
- Note that the sprite didn't really change though.

**Comment by KillianKirilenko** [comment] 2021-07-17 09:22
Duplicate of #10172. On my to-do list, will look into it over this weekend.

**Closed** 2021-07-17 14:23 UTC
