### ISSUE TITLE
Citalopram pill makes you unstable

### ISSUE THREAD

**Issue by TheDavestDave** [VOREStation/VOREStation#3791] opened 2018-05-29 14:04 UTC
#### Brief description of the issue
Citalopram doesn't give any postive effects when injested
#### What you expected to happen
some kind of positve effect

#### What actually happened
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
our mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
our mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
someone saying something important 
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
our mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
our mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
Your mind feels a little less stable...
#### Steps to reproduce
- (Step 1) Take 5 unit Citalopram pill
- (Step 2) SPAM!

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
2616b963a0136fe21106af82982914ec8c1db2b9 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Ketrai** [comment] 2018-06-02 07:45
I think you took too much. Or too little, it's more complicated than you think.

/datum/reagent/citalopram
	name = "Citalopram"
	id = "citalopram"
	description = "Stabilizes the mind a little."
	taste_description = "bitterness"
	reagent_state = LIQUID
	color = "#FF80FF"
	metabolism = 0.01
	mrate_static = TRUE
	data = 0

/datum/reagent/citalopram/affect_blood(var/mob/living/carbon/M, var/alien, var/removed)
	if(alien == IS_DIONA)
		return
	if(volume <= 0.1 && data != -1)
		data = -1
		M << "<span class='warning'>Your mind feels a little less stable...</span>"
	else
		if(world.time > data + ANTIDEPRESSANT_MESSAGE_DELAY)
			data = world.time
			M << "<span class='notice'>Your mind feels stable... a little stable.</span>"

From what i've gathered, it's supposed to say your mind feels stable after a while. Tbh, this is a pretty memey antidepressant, but without any comments I'd have to go back and check when it was implemented to know wether it's supposed to work like this or not.

**Comment by Screemonster** [comment] 2018-06-08 04:46
Duplicate of #3373

**Closed by Screemonster** 2018-06-08 04:46 UTC
