### ISSUE TITLE
Windows in engine room are completely wrong.

### ISSUE THREAD

**Issue by Heroman3003** [VOREStation/VOREStation#4389] opened 2018-10-14 07:39 UTC
#### Brief description of the issue
Tesla submap has all windows broken and wrong

#### What you expected to happen
Normal windows

#### What actually happened
http://prntscr.com/l5v5w4

#### Steps to reproduce
- Look at it

#### Code Revision
- 1fe04192c11e2ad7357512d5a873c44a4ea687d3 
 
#### Anything else you may wish to add:
With same issue present in SM, going to assume its something about engine submap being loaded in.

**Comment by Screemonster** [comment] 2018-10-14 10:05
looks like it's loading in single-pane instead of fulltile windows.

**Comment by Screemonster** [comment] 2018-10-14 10:08
Gonna close this as it's effectively a duplicate of #4382

**Closed by Screemonster** 2018-10-14 10:08 UTC
