### ISSUE TITLE
Dropping one sheet on top of another one sheet.

### ISSUE THREAD

**Issue by Nomium** [VOREStation/VOREStation#8103] opened 2020-05-28 18:09 UTC
#### Brief description of the bug
Dropping one sheet of material onto another one sheet of same material causes them to be destroyed somehow.

#### What you expected to happen
I thought two sheets of one same material could exist on one tile?

#### What actually happened
I dropped two one steel sheets on to one tile and they vanished completely, not turning invisible.

#### Steps to reproduce
- (Step 1) Grab sheet of material and pull two one sheets from it.
- (Step 2) Proceed to drop both one sheets onto each other on the same tile.

**Comment by KasparoVy** [comment] 2020-05-28 19:14
Related to #8102

PRs #7960, #7920

**Comment by Shadow-Quill** [comment] 2021-02-08 18:09
Seems to be a close duplicate of https://github.com/VOREStation/VOREStation/issues/7991

**Closed** 2021-11-23 04:28 UTC
