### ISSUE TITLE
Xenomorphs

### ISSUE THREAD

**Issue by SilverTalismen** [VOREStation/VOREStation#622] opened 2016-10-02 22:44 UTC
#### Brief description of the issue

Xenomorphs have none of their abilities, being just simple mobs anyone thta possesses them has no Nightvision or powers of any sort
#### What you expected to happen

To atleast have nightvision or something
#### What actually happened

Blind as a bat in the dark, and no abilities
#### Steps to reproduce

Spawn any of the xeno mobs, take control, Be unable to do anything actually useful and be blind in the dark.
#### Additional info:
- **Server Revision**: release - 2016-10-02
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment] 2016-10-03 00:39
I don't want to use xenocode from the old code, but rather the REALLY old xeno code from Bay code. Like, before it was shit.

**Comment by SpadesNeil** [comment] 2016-12-10 20:58
Duplicate of https://github.com/VOREStation/VOREStation/issues/15 I just realized.

**Closed by SpadesNeil** 2016-12-10 20:58 UTC
Labels: Type: Feature, Type: Old Code Port
