### ISSUE TITLE
More camera console tag bloopers.

### ISSUE THREAD

**Issue by Verkister** [VOREStation/VOREStation#3602] opened 2018-04-29 20:01 UTC
#### Brief description of the issue
There are still some/new camera console tag anomalies.
-Command meeting room east shows up as dupe of HoP Office.
-Chemistry lab shows up as dupe of MED Break Room East.
-Medbay recovery room shows up as dupe of MED Break Room West.
-Northwest corner and southwest corner of atrium first floor are duping each other as camera number 276.
-Warden equipment storage south shows up as dupe of HoS office.

#### What you expected to happen
Proper tagging.

#### What actually happened
Something else.

#### Steps to reproduce
- (Step 1) Do a checkup on camera monitoring console.
- (Step 2) Trip and tumble a few more times onto misbehaving buttons.

#### Code Revision
- b18bbb45ba09571d1a0489423f3f6efd6590fd4b
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Arokha** [comment] 2018-04-30 15:48
- [ ] Command meeting room east shows up as dupe of HoP Office.
- [ ] Chemistry lab shows up as dupe of MED Break Room East.
- [ ] Medbay recovery room shows up as dupe of MED Break Room West.
- [ ] Northwest corner and southwest corner of atrium first floor are duping each other as camera number 276.
- [ ] Warden equipment storage south shows up as dupe of HoS office.

**Comment by Arokha** [comment] 2018-04-30 15:53
The numbered ones, 276, are actually randomly generated between 111 and 999, so that's a pretty big coincidence, but is unlikely to be repeated.

**Closed** 2018-04-30 23:31 UTC
Labels: Type: Map
