### ISSUE TITLE
Synths getting drunk without taking the ethanol simulator trait.

### ISSUE THREAD

**Issue by SatinIsle** [VOREStation/VOREStation#14792] opened 2023-04-14 19:34 UTC
#### Brief description of the bug
Synths get the effects of being drunk without taking the ethanol simulator trait. 

#### What you expected to happen
Synths that have not taken the ethanol simulator trait should be immune to the effects of alcohol.

#### What actually happened
As my character, Non Beta, who is fully synthetic, I drank a fair amount of deathbell. Something that she can usually do fine, but this is the first time since the ethanol simulator trait was added. Upon drinking the deathbell, she became very drunk. She has not taken the ethanol simulator trait (nor the ethanol burner trait that was added at the same time). Purging reagents did not end the effects. 

#### Steps to reproduce
- Play as a synth character, be sure NOT to take the ethanol simulator trait.
- Drink deathbell (only tested with that drink, may be a specific issue).
- Become drunk when you shouldn't be.

#### Code Revision
Server revision: B:release D:
Commit: [92c6068f6768a404a59e2aeb9843603874316f79](http://127.0.0.1:49935/tmp14008/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/92c6068f6768a404a59e2aeb9843603874316f79%22%3Ehttps://github.com/VOREStation/VOREStation/commit/92c6068f6768a404a59e2aeb9843603874316f79%3C/a%3E)
 

#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/98125273/232138302-04e12b67-0ac7-436b-a528-7df708575e8d.png)
![image](https://user-images.githubusercontent.com/98125273/232139178-5fbfc100-66d7-49b6-aa03-0c1576593bc2.png)

**Comment by KillianKirilenko** [comment] 2023-04-14 22:06
Duplicate of #14773

**Closed** 2023-04-15 11:15 UTC
Labels: Type: Bug
