### ISSUE TITLE
[UI] TGUI chat and disabling the deletion of old messages causes PC freezes

### ISSUE THREAD

**Issue by AzzyDreemurr13** [VOREStation/VOREStation#15604] opened 2023-12-12 14:29 UTC
#### Brief description of the bug
Due to the new chat and disabling the memory cleanup function (apparently you did not fully optimize the TGUI chat), it is impossible to play Vorestation on weak PCs, unlike other servers

#### What you expected to happen
TGUI chat does not cause lags as on other optimized servers(Tau Ceti, SS220 (Paradise), bluemoon, TG Station - where there are more rounds, as well as battle logs and so on, which last from 1 hour and 30 minutes to 3 hours)

#### What actually happened
The PC is going crazy (freezes, lags and freezes) from the memory overload caused by the new chat. **I want to note** that there were never such values on the old chat and there was about 100-200mb of load.
![image](https://github.com/VOREStation/VOREStation/assets/74739991/a3c4428f-7f68-45c7-a0f2-2742410839cb)
Russian words in screen:
ЦП - CPU
Память - Memory 
МБ - MB

#### Steps to reproduce
- Play for about an 30-50 min
- wait for the friezes to start and watch the task manager blink red in memory section

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ItsSelis** [comment] 2023-12-13 14:03
Duplicate of https://github.com/VOREStation/VOREStation/issues/15599

**Closed by ItsSelis** 2023-12-13 14:03 UTC
Labels: Type: Bug
