### ISSUE TITLE
Either fix grubs or remove them. Please. *Please*.

### ISSUE THREAD

**Issue by chaoko99** [VOREStation/VOREStation#6043] opened 2019-10-09 06:50 UTC
Primary thing that's come up is something like making them not able to appear in critical areas (which is something set on the area itself as a variable), but that would likely only lead to them not spawning there, instead entering due to the way that pipes work for mobs.

Another thing is that they are still not really something you can find before it's too late, not easily. Peiople have suggested having htem raise alarms.

- The arguments I've heard for keeping grubs: 
- They only appear when people are there to deal with them
- They're easily countered by substation setting.
- They "Give enginering something to do".
- "They're not as common as they used to be" (this isn't even an argument)
- apparently something good can come from "improve don't remove" when nobody will improve.

Arguments against grubs:

- They literally scene-stomp. Something we ban people over, but is mysteriously acceptible because the game is doing it. They do this by appearing IN THE ENGINE ROOM, forcing people to leave what they're doing or face round ending.
- They tend to appear towards the end of the round due to their prerequisites of a mildly high population to have a reasonable chance of rolling
- they do not scale to player pop at all. 
- The map is designed in such a way to make finding them as frustrating as possible (various subnets account for 70% of 3 Z levels)
- The best way to deal with grubs is to ignore them so someone else can deal with them, as they're really only an issue when put in hazardous locations.
- Nobody seems willing to fix them.

----------------------------------------------------------------------------------

I'm getting really tired of dealing with grubs. It's making me want to quit playing Engineering. I've seen engineers cryo when hte event pops. It's just boring. It's annoying. And it requires cooperation to deal with easily. Nobody wants to cooperate.

**Comment by chaoko99** [comment] 2019-10-09 06:51
After a solid year of dealing with grubs I have completely failed to locate the fun in grubs. I'm sorry.

**Comment by Heroman3003** [comment] 2019-10-09 07:01
As annoying as grubs can be... In my experience they never resulted in anything actually critical. Even spawning in the engine room they induce more panic than they do harm. On SM setup they are pretty much harmless. On Tesla setup they are either latching onto power distribution wire, which will not affect emitters as they will fire still as long as power is THERE, making grub lesser priority, or they will latch onto power supply wire, but because of their positioning they don't actually disrupt overall flow, only eating some of the excess from the production.

There was a recent incident where it was believed that a grub larva climbed into Engien SMES and emptied it resulting in Tesloose but... Thats absolutely not how grubs even work. Even when they climb into SMES or any power-storing device, they will drain power from local network (aka APC) rather than device itself, which in case of SMES room is entirely harmless. Adult grubs only latch on to wires, becoming more of a nuisance, but still safe and easier to detect. It could not have been a grub that one time.

I don't think grubs are too much 'fun' but neither is literally ANY random event in the game, and amount of hate they get is really really disproportional to amount of supposed 'disruption' there is. Which is usually pretty small if people who are free are just doing what they are supposed to. There were several times where I was in a scene as one of two or even only acting engineer and just let grubs fester because the only places they will affect are places that are not used in the first place, since if place is used, people will kill any grub in it.

**Comment by chaoko99** [comment] 2019-10-09 07:03
Short, quick response: I believe our perspective differs significantly. I tend to spend my rounds roleplaying, where I do not think I have ever observed you doing anything but engaging in mechanics. AFKing for long stretches of time. It just seems like we have different playststyles. I don't want to deal with grubs. They're a pain for me.

**Comment by chaoko99** [comment] 2019-10-09 07:05
Also: RE emitters. 

That tesla did escape. It was almost round ending, but we got good RNG and it flew into space.

**Comment by Heroman3003** [comment] 2019-10-09 07:07
And as I said, if it really was in SMES room, there is no way it could have been the cause. And as we all know, there are potential ways one can screw up the Tesla setup that it doesn't escape immedeately and instead with a notable delay. I can see grubs accelerating that delay, but not being sole cause. And you admitted that you had no idea how exactly it was set that one round.

**Comment by Chargae** [comment] 2019-10-09 07:11
Grubs are one of the primary reason Engineering becomes more of a chore than a fun role.

Want to play an engineer and have a scene? Grubs will inevitably fuck up your scene.

Want to play an engineer and build a project? Guess what you'll have to spend half an hour chasing around when nobody wants to deal with the damn things cos they're busy humping eachother.

It's like spam. Annoying. It doesn't _add_ anything to any round except something that's irritatingly predictable, the only difference being that the grubs actually affect the station itself.

**Comment by Very-Soft** [comment] 2019-10-09 07:25
I think the arguments for removing grubs essentually amount to 'something happened that might require me to actually do something and I don't like that' And, I think sort of needing to go an check the main SMES room and maybe weld the vents there is a lot easier and more tolerable to attend to when you've got a scene to return to, than, say, hunting down the right vending machine to stop all the other vending machines from throwing shit at people. (Or to run around fixxing all the malfunctioning ones individually when people complain about them)

Now, that's not to say I don't think grubs could be improved, but! I think the main issue with grubs is that they are an every shift problem.
I personally like hunting grubs. Especially if I'm on a deadshift with nothing to do? It's fun to figure out where they are and work with others to go kill them.
But for sure, I think I'd like them more if they happened like, once a day, or even once every few days. (See: Not every single shift)

The problem is quite simply that we don't have enough random events for the random events to not cycle through all of the events we have active every shift.

I'd honestly really like to see a bunch of variants on existing events to fill it out more, so that events like grubs by proxy become less common due to saturation.

Grubs can be a bit annoying, but apart from -one room- on the whole station, you can honestly just ignore them and let other people deal with them if they're fussed about it and you're busy with something.

**Comment by chaoko99** [comment] 2019-10-09 07:36
>I'd honestly really like to see a bunch of variants on existing events to fill it out more, so that events like grubs by proxy become less common due to saturation.

Okay, and for the sake of argument: What about when this inevitably does not happen?
Because I'm fairly sure it won't.

>But for sure, I think I'd like them more if they happened like, once a day, or even once every few days. (See: Not every single shift)

We're already post "rarity increase".


Also Heroman, I'd like
>Short, quick response: I believe our perspective differs significantly. I tend to spend my rounds roleplaying, where I do not think I have ever observed you doing anything but engaging in mechanics.

addressed. Do you think this might cause a difference inperspective?

**Comment by Heroman3003** [comment] 2019-10-09 07:40
Not really. While I do end up idling more often, admittedly... Grubs still end up extremely ignorable thing. Honestly, with their spawn amounts nerfed after being brought back, any feeling of urgency or severe need to deal with them has waned, regardless of whether I am half-afking, wandering around, engaging in casual RP or full on busy in a scene.

**Comment by Very-Soft** [comment] 2019-10-09 08:28
> > I'd honestly really like to see a bunch of variants on existing events to fill it out more, so that events like grubs by proxy become less common due to saturation.
> 
> Okay, and for the sake of argument: What about when this inevitably does not happen?
> Because I'm fairly sure it won't.
> 
> > But for sure, I think I'd like them more if they happened like, once a day, or even once every few days. (See: Not every single shift)
> 
> We're already post "rarity increase".

I don't think you read what I wrote, so I'll make it shorter for you:

I think grubs are cool, but happen too often. I would like it if they happened less often. The reason they happen so often is because we don't have enough events for them to happen any more rarely.

-

But to add to what I was saying, I think that if we get into the habit of removing inconvenient elements from the game just because they're annoying sometimes, that we may as well just remove the whole random events lineup, because that basically describes everything that can happen in there.

Grubs -for the most part- aren't really more trouble than, say, a meteor blowing up the glass of the bar, or a vending machine randomly deciding it would like to throw knives at people.

I will say that grubs probably shouldn't be spawning in the engine SMES room, certainly. But I also don't think it's such a terrible ask for, when you see the grubs announcement, to head to engineering and check, or to run to atmos and peep via the cameras. Outside of that one room, grubs are no more harmful than any other inconvenient events, and easily combatted. Outside of checking to make sure that that one room isn't compromised, if you're busy with a scene, no one's really gonna be all that inconvenienced by grubs being in random nooks and crannies about the station.

And as you mentioned. If you set up the RCON properly, the only places that'd lose power would be the places with grubs in them. Just saying. Part of the purpose of having the subgrids is to manage the power. You don't -have- to deal with it, sure, but it's not like the thing isn't there specifically to detect and deal with abnormal power fluctuations.

**Comment by Screemonster** [comment] 2019-10-09 11:01
"I didn't set the subgrids properly and now the entire station is getting drained instead of the couple of places that have grubs, which we can identify from the power drain"

Grubs don't spawn in the engine but I think the issue is that they spawn near it then ventcrawl in.

It'd be _nice_ to see them generate power alarms by existing, rather than having to wait until an APC drains ('cause the power alarms they create aren't necessarily the room they're in - they prevent APCs charging rather than directly draining them, so if another room in the department has a heavier draw that room will get the alarms first)

**Comment by TheDavestDave** [comment] 2019-10-10 12:00
Grins aren't fun to deal with and they sure as hell aren't fun to deal with every shift. As stated. Most random events get removed because they aren't fun. To deal with every shift. Engineering tends to on scream at other departments to remove grubs and some will refuse to leave engineering and just cut off power instead of hacking into the heads office to get the grub like asked. 

If there is active engineering too. This seems to be engineering abduction event. Maybe if other things happened it could be fun again but it may just be pushing people away.

**Comment by Ketrai** [comment] 2019-10-10 21:43
Chaoko's monthly complaint about grubs everyone. Honestly at this point just pr a change for the feature yourself if you're so tired of them.

**Comment by Ketrai** [comment] 2019-10-10 21:47
Or even better. Add inert grub larvae as their own event (call them grub rejects. Aka members of the grub colony that got scared away due to genetic defects) with a 5% chance of the event also activating the main grub even. Then disabling the main grub event.

**Comment by SpadesNeil** [comment] 2019-10-11 02:09
>Chaoko's monthly complaint about grubs everyone. Honestly at this point
just pr a change for the feature yourself if you're so tired of them.

As much as I want to scold Ketrai for what comes off as a mean spirited
post.

But, don't bother with a removal PR. I will reject it. I have said several
times that I am ignoring demands to remove grubs. Attempt to make them
better before we fucking delete them. I think removing vent crawl from
grubs is a reasonable thing to do, for example.

**Comment by SpadesNeil** [comment] 2019-10-11 02:15
For fuck's sake email ate my post.

I was saying: As much as I want to scold Ketrai for what comes off as a
mean spirited post, they have a point about this issue being useless
complaining. There's no suggestions at a solution in the original post.
Just complaining and demands to delete. I already said this elsewhere like
on Discord, I'm just repeating myself here for the sake of record. Forgive
me if I am now beating a dead horse.

For the rest of what I wanted to say, see prior comment.

Also Ketrai, be less of a dick please. You make a point but you could have
said it in a far less dickish manner. I would say the part about telling
them to make a PR on their own if they're so sick of them is a valid
statement. Saying how it's a "monthly complaint" is not really kosher,
though.

**Comment by Ketrai** [comment] 2019-10-11 08:51
Sorry ace, just getting a hit tired of seeing this discussion again and again, but that's indeed not an excuse to be harsh like that. And currently grubs borrow spiderling code as in they spawn in vents and then crawl out of them. This is done so you don't get magically manifesting grubs anywhere if you happen to be in the room. Could change this by making it spawn grub nests instead, or something.

**Comment by Wickedtemp** [comment] 2019-10-11 17:44
Engineering gets all of the random events.

Greytide in Brig/Viro? Engy fix it.
Vendors shooting stuff? Engy fix it.
Space dust broke a window! EnGY FIX IT!
METEROID HIT BAR ENGY FIX.
GRUBS. ENGY FIX! FIX NOW!

I think it would be beneficial if we recognized that this can be annoying to deal with. Not as a "OH LOOK AT YOU CRYING CAUSE YOU GOTTA DO JOB", because while that *is* something of a valid point for Medical as my primary example, I'd wager its easier to fix a few crit patients than it is to wander around every department on every floor looking for the bad vendor, or going through departments to get rid of grubs, doing it all by yourself because nobody else in Engineering feels like it, and having to hack your way in because people don't want to stop their own scene to sweep their own department. I've seen several of these events trigger one after another, causing the lone engineer to just fucking leave.

Yes, its ""part of the job"", but we have people that primarily play that job saying it isn't fun. Maybe its fun for someone who doesn't play Engineering most rounds because for them its "oh hey we can go grub hunting!", because for them, its not an everyday chore. Just like how I don't mind, because all I have to do is sweep Medbay with a toolbox. It doesn't affect me. Chaoko minds because they have to sometimes sweep the entire station. 

So, small things to add to the event to make it less annoying? A fixed "3 Active Engineers", else it can't fire. Or a requirement for other departments, else grubs cannot appear in those areas. 

And while I understand "we shouldn't remove things just cause people dont like it every single time".. nobody's saying that. One time is different than every time. All it takes for this to not set precedent is for you to say so. As far as I can tell, grubs don't add anything that we can't implement in less annoying ways. The entire problem is that theyre a nuisance to one specific department and "arent a big enough deal to get others involved but still big enough that its annoying as fuck and if i dont fix it im not doing my job and risk IC/OOC consequences for intentionally ignoring it"
 The only things people liked about the grubs is that it was something small and weak to hunt and sometimes let yourself get killed by.

So...why not remove the APC draining, or limit how much of an APC they can drain.

**Comment by TheDavestDave** [comment] 2019-10-11 18:31
A carp event would be better than a grub event.......other than how robust they can be Becuase they cause damage for engineering to fix, give sec something to do, can be ignored-ish, and give medical rare chems. Geese would be a good sub too.  The power thing makes grubs everyshift bad. I think it is better admin spawned than random spawned

**Comment by Heroman3003** [comment] 2019-10-11 18:35
The difference with those is that they are actively hostile and when not dealt with can cause damage that requires much more work than just removing the source (breach vs just a power vacuum that will fix itself once grub is dead)

**Comment by Chargae** [comment] 2019-10-11 21:07
There's fairly regular complaints about grubs. Nobody seems to want to fix them, which means it's going in a circle of "Grubs are lame" "We don't care"

It's not the simple fact of "oh it's busywork", it's busywork that if you ignore, you get bitched out for it, even if you were in a scene, which, as far as I'm concerned, that's the primary purpose of a HRP server, isn't it?

It can lead to situations like "Hey, engines set, let's chill out and have a scene"
Then grubs appear. Then once you're done dealing with grubs, somehow a "pipe bursts" in maint, and fills a room with phoron, or sleeping gas. Then while you're trying to deal with that in an area with no scrubbers or vents (Though that might have been fixed since it happened to me) some other crap goes down, and as an engineer, you're expected to fix everything at once, by yourself, and it's just not a fun or compelling experience.

If someone wanted to fix the grubs, they'd probably have been fixed months ago. Keeping something in just because "removing features is bad" is... I guess, a way of doing things, but I don't really agree with it.

And yeah, I guess I'm part of the problem if I don't want to dive into Byond, learn how to navigate the hot mess that is SS13 code just to fix an event I never liked in the first place.

**Comment by SpadesNeil** [comment] 2019-10-11 21:51
What if we altered grubs to only fuck up a single room at a time? So they could be ignored without any massive consequences.

Technically you can do that already if you aren't a tard and bother to set the SMESes for the different grids, but even then it only covers one grid at a time.

**Comment by Heroman3003** [comment] 2019-10-11 21:53
Tbh, I agree with general idea. Random events are not fun. None of them are. My main disagreement in the first place was with idea of "Solargrubs are awful". They aren't any more awful than any other random event we have that is nothing more than poking engineers with chores. There's nothing fun about fixing random gas leaks, fixing random canister pops, playing waiting game on telecomms or PDA spam, or having to just come and unbolt or, if you were in engineering and already free when it happened, unpower brig/virology. Hunting grubs is exactly as engaging and 'fun' as all of the above. Not any better, but not any worse either.

**Comment by Screemonster** [comment] 2019-10-11 21:58
> Engineering gets all of the random events.
> 
> Greytide in Brig/Viro? Engy fix it.
> Vendors shooting stuff? Engy fix it.
> Space dust broke a window! EnGY FIX IT!
> METEROID HIT BAR ENGY FIX.
> GRUBS. ENGY FIX! FIX NOW!

to be fair, medical get enough "random" work from the crew just doing their own thing, as do security, as do supply and service, and science largely make their own fun. Without random events, unless you have a construction project in mind, there isn't much for engineers to do after roundstart.

**Comment by TheDavestDave** [comment] 2019-10-11 23:21
I don't think geese would be more disruptive than the grubs, seeing as if the whole player base ignores or can't find the goose nothing happens. While if if no one removes or find the grub the whole department, or in some cases floor, is without power.

I guess another way to make grubs better would be to nerf power drain to the ground so that engineering could just go, eh I'll just give the area more power

**Comment by TheDavestDave** [comment] 2019-10-11 23:27
> Technically you can do that already if you aren't a tard and bother to set the SMESes for the different grids, but even then it only covers one grid at a time.

yeah no ace, they will drain the whole department so no one can use it. And think about how much of the station is on the civ grid

**Comment by SpadesNeil** [comment] 2019-10-11 23:28
>yeah no ace, they will drain the whole department so no one can use it. And think about how much of the station is on the civ grid

no I get that

I was talking about restricting the drain to a single APC, basically just fundamentally changing how grubs affect the grid.

Instead of making them power sinks, make them EMP the local APC.

**Comment by TheDavestDave** [comment] 2019-10-11 23:32
I don't personaly like it, but it's much better than what they do now

**Comment by SpadesNeil** [comment] 2019-10-12 01:10
Okay well there's an idea because "DELET THIS" is not an option.

This thread is awfully cluttered so I'm going to close it. We'll continue this in a new discussion about how to improve Grubs.

**Closed by SpadesNeil** 2019-10-12 01:10 UTC
