### ISSUE TITLE
Expedition Shuttle Airlock is broken.

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#3050] opened 2018-02-17 09:44 UTC
#### Brief description of the issue
The airlock on the expedition shuttle keeps getting screwed over, resulting it never fully pressurizing.

#### What you expected to happen
The airlock being able to pressurise and depressurise without issue.

#### What actually happened
Various atmospheres screw the airlock over, resulting in broken pressurization that never comes to an end due to a lack of air. 

#### Steps to reproduce
1. Go to the expedition shuttle and take off.
2. Go to a planet with a horrible atmosphere. IE: Virgo 2.
3. Cycle the airlock to go out onto Virgo 2.
4. Come back inside and head back to the station.
5. Watch in anger as the docking sequence doesn't finish due to the airtank being filled with overheated carbon gas instead of air.

#### Code Revision
f9feb190c403c43650399fb5a4558187d5d155be 
 
#### Anything else you may wish to add:
N/A

**Comment by Arokha** [comment] 2018-02-17 09:58
Unusual. Cycling in dumps all the atmosphere outside, not into the tank.

**Comment by aztectornado** [comment] 2018-02-17 10:04
This happens often too. Not sure what causes it, rounding errors? 

Either way, this is why I keep the air pump in there; it repressurizes the thing when it doesn't fill enough.

**Comment by Arokha** [comment] 2018-02-17 10:09
Can't reproduce it. Works fine for me when I fly to Virgo 2, cycle it in and out.

**Comment by HzDonut** [comment] 2018-02-17 23:31
Having been on multiple expeditions to Virgo 2 now I can confirm that the airlock likes to break after a couple of cycles, usually two or three will do it.

**Comment by aztectornado** [comment] 2018-02-19 08:55
You have to cycle it several times.

**Comment by aztectornado** [comment] 2018-02-21 22:34
This occurred again yesterday. It appears to be something that happens after multiple trips. Decimus was on and I called them to look at it, so they can attest that it is a real thing, though we're not sure why it's happening.

my current theory is that the controller gets confused or something, and when draining the lock of internal air, treats it as if it were external by dumping it, or perhaps loses the air in transit by not sealing the outer door properly or something. (though why the tank empties too is a mystery in that case)

**Comment by Arokha** [comment] 2018-02-22 18:15
The tank would decrease over time due to there being a threshold of a few kPa that it's willing to 'sacrifice' in the interest of cycle time. But shouldn't be too much. I noticed it's very slow to fill that tank, too, because it's highly pressurized, which makes me think it's not dumping it most of the time.

Maybe only sometimes? I'm not sure.

**Comment by Screemonster** [comment] 2018-02-22 18:46
Short of giving the station its own little mini set of atmos filters and scrubbers and things and ways to cycle and purify air the way the station airlocks work, there's not really an easy way to solve this in all cases. Like, if it loses pressure you _could_ try to pump air in from outside, but that wouldn't work in space and in unbreathable atmospheres would also contaminate the shuttle the next time you pressurised the airlock.

**Comment by aztectornado** [comment] 2018-03-20 18:04
Is this still a thing? I haven't explored in a while. 

If so, at this point I think we should just map a second docking/airlock controller somewhere in the expedition shuttle and let the teams sort out what's wrong and how they're gonna fix it.

**Comment by Mewchild** [comment] 2018-05-20 05:46
https://i.imgur.com/vh9E6YZ.gifv
Current Code revision: c973f8672a981994941b90fc583c88c1ddab5fac
The issue is that when the airlock cycles, the atmosphere from inside the airlock is dumped outside the ship. This leads to the canister being emptied over time. When this happens, the airlock is unable to finish cycling, as it's not able to replace the air within the chamber. It doesn't matter how much air is in the canister/tank initially, it **will** be emptied by multiple docking/undocking attempts. @Arokha

**Comment by Mewchild** [comment] 2018-05-20 05:57
In the following images, all I've done is hit the undock, and then the dock button on the shuttle. It's still within the hangar. As this was happening, the dock was overpressurizing, as the airlock atmos was being pushed outside the shuttle. Every iteration, you're losing 436kPa of air from the canister, and when you have less than that amount, the cycle fails.

Fresh Tank, just refilled: 
![image](https://user-images.githubusercontent.com/13400422/40276123-48a8dfd6-5bc7-11e8-8ad3-0bbcb78044d0.png)

Undocked, then docked again, once: 
![image](https://user-images.githubusercontent.com/13400422/40276131-7a9f1762-5bc7-11e8-9e2d-f499fce1cc97.png)

Twice: 
![image](https://user-images.githubusercontent.com/13400422/40276137-a7cef572-5bc7-11e8-8ffc-898e3df33023.png)

Three times: 
![image](https://user-images.githubusercontent.com/13400422/40276147-e37694b8-5bc7-11e8-8aeb-19fa2ea06d4a.png)

Four times: 
![image](https://user-images.githubusercontent.com/13400422/40276163-3d3bc374-5bc8-11e8-87d1-eec698d483a9.png)

Five times: 
![image](https://user-images.githubusercontent.com/13400422/40276174-74dc45c4-5bc8-11e8-841f-671eec978e0a.png)

And Six times, where the cycle finally chokes and fails: 
![image](https://user-images.githubusercontent.com/13400422/40276179-b9959eea-5bc8-11e8-99cb-c772aa8063ad.png)

**Comment by TheDavestDave** [comment] 2018-05-20 14:02
The problem is due to air escapeing the cansiter. Currently the canister doesn't start with enougth air and I have to hack the door to get air in the system

**Comment by Arokha** [comment] 2018-05-20 15:00
We should probably go back to the big tank because it had more air, but this seems to be a flaw with the airlock, @Leshana 

Seems like it dumps internal air to space even when doing in->out?

**Comment by Novacat** [comment] 2019-09-19 19:37
Fixed with the new expedition shuttle. Mostly.

**Closed by Novacat** 2019-09-19 19:37 UTC
Labels: Status: Resolved
