### ISSUE TITLE
Having the haste trait and using the wheel chair = mach speed

### ISSUE THREAD

**Issue by MrSign** [VOREStation/VOREStation#4440] opened 2018-10-20 21:59 UTC
#### Brief description of the issue
If you pick the haste trait as a custom species and use a wheelchair, you will become The Flash from DC Comics.

#### What you expected to happen
To be slowed down heavily because rolling around in a wheelchair is slow.

#### What actually happened
MOVING AROUND AT THE SPEED OF SOUND! GOT PLACES TO GO!

#### Steps to reproduce
-Set up a custom species that has the haste trait.
-Select wheelchair in the loadout section.
-Spawn in and set up your wheelchair.
-Buckle into wheelchair and start moving around.
-WOAH SHIT, I'M SONIC!

#### Code Revision
1fe04192c11e2ad7357512d5a873c44a4ea687d3
 
#### Anything else you may wish to add:
N/A

**Comment by Mewchild** [comment] 2018-10-20 22:08
Do you still move this speed without haste? Re: https://github.com/VOREStation/VOREStation/issues/3556

**Comment by Mewchild** [comment] 2018-10-20 22:28
Did testing. Duplicate of above mentioned issue

**Closed** 2019-04-08 00:59 UTC

**Comment by TheFurryFeline** [comment] 2019-04-08 01:03
For reference, even though this is now closed, I nerfed this with #4759
